### ISSUE TITLE
Map tooltip show and hides on mobile/narrow screen or is partially visible

### ISSUE THREAD

**Issue by jalezi** [sledilnik/zdravniki#87]
If marker's tooltip height is near map height, tooltip pushes marker outside the map and consequently disappears (fully zoomed in). 

Steps to recreate:
1. go mobile or narrow screen (viewport height around 590px)
2. find "Ribič Bojan"
3. click on marker icon in doctor card (it will fully zoom in and position marker in center.
4. try to get tooltip

Video was recorded on iPhone SE 2.

https://user-images.githubusercontent.com/44704999/144999872-d5dfe605-270e-40a4-baa3-87b4c7a60a7a.mp4

When map is zoomed out then due to map max bounds tooltip pushes marker down trying to fit on the map and then marker snaps back and tooltip is not fully visible.

Steps to recreate:
1. steps 1 - 3 from previous (viewport height around 736px - iPhone 6,7,8 plus)
2. fully zoom out
3. try to get tooltip

![localhost_3000_sl(iPhone 6_7_8 Plus) (1)](https://user-images.githubusercontent.com/44704999/145005497-63ff1428-a71a-41a1-a7ff-24b5288a41bb.png)

**Comment by stefanb** [comment]
With #73 we fixed #30 but could make the bounds a bit larger to make room for more baloons 🎈🎈🎈🎈
We could tweak the min zoom level.
We could make the baloon smaller (eg "ne sprejema" is redundant, as it can be seen also from the marker colour, although not friendly for the colour-blind users)

**Comment by jalezi** [comment]
Max bounds are definitely a problem. Not only on mobile. Try to center Murska Sobota (it think from zoom 12 you can). With max bounds there is also another problem. Fully zoomed in the user can still get lost. Maybe we can notify user if he is past last marker.

I mentioned "ne sprejema" once and @lukarenko has same argument - colour-blind.  I guess the size of the balloon was the reason why I used to have button.

Can we somehow shorten institution names? In case of "Ribič Bojan" takes 4 lines in balloon. On the other hand we can tweak the balloon style. There is some room to make it smaller: line-height, font-size, "Zdravnik" is not needed and maybe something else.

**Comment by lukarenko** [comment]
@jalezi you can just shorten autmtically if more than 30 characters or so and use ...

**Comment by lukarenko** [comment]
Otherwise @bananica had some suggested preview for tooltips

**Comment by bananica** [comment]
indeed:
![PixelSnap 2021-12-08 at 09 45 09](https://user-images.githubusercontent.com/6833025/145177163-54e81184-f693-4246-9715-15e5e1b3a45f.png)

**Comment by jalezi** [comment]
I believe we can close this one. I am pretty sure it solved with new design #102.
Tooltip styling issue is already in #105.
